
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dragonTwo?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver