server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dragon?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password:
    database: 2
    timeout: 6000
logging:
  level:
    com.traveler.dragon: INFO
aj:
  captcha:
    jigsaw: classpath:images/jigsaw
    pic-click: classpath:images/pic-click
    cache-type: redis
    type: default
    water-mark: \u6211\u7684\u6c34\u5370
    slip-offset: 5
    aes-status: true
    interference-options: 2
    history-data-clear-enable: true
    req-frequency-limit-enable: true
    req-get-lock-limit: 5
    req-get-minute-limit: 30
    req-check-minute-limit: 60
    req-verify-minute-limit: 60