server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dragonTwo?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password:
    database: 2
    timeout: 6000
logging:
  level:
    com.traveler.dragon: INFO
mybatis-plus:
  mapper-locations: /mapper/*.xml
  type-aliases-package: com.traveler.server.model.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false

### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；

dragon:
  admin:
    address: http://127.0.0.1:8080/xxl-job-admin
  accessToken:
  executor:
    appname: xxl-job-executor-sample
    address:
    ip:
    port: 8081
    logpath:
    logretentiondays: 30
